---
title: "lecture11"
author: "Shengtong"
date: "2018-11-12"
output: workflowr::wflow_html
runtime: shiny 
---

```{r, echo=T, eval=F}
########################################################
#### Read https://deanattali.com/blog/building-shiny-apps-tutorial/
####
#### Still working on projects
####
#### HW7 (last one!) due next week
######################################################


#=============================================================
## Interactivity in R: In-class slides
#=============================================================

#-------------------------------------------------------------
## In class:
## 1. Create several ggplots of the iris data (scatterplot,
##   histogram, boxplot, ...) 
## 2. Experiment with changing the hover-over information with tooltip
#-------------------------------------------------------------

library(tidyverse)
library(plotly)

#=============================================================
## Shiny:
##
## R package from RStudio that is a web application framework for R
## R code -> interactive web page (no HTML/CSS/Javascript knowledge required)
##
## Let's look at http://www.showmeshiny.com/ for some ideas
#=============================================================

library(shiny)
runExample("01_hello")

## Shiny apps are composed of two parts: 
##   (1) web page that shows app to user = UI (user interface)
##   (2) computer that powers the app (either your own or on a server somehwere else) = server

## Tutorial we'll follow in class:
## https://deanattali.com/blog/building-shiny-apps-tutorial/
```



```{r, echo=T, eval=F}
## Lots of other helpful stuff:
##
## Layout guides: http://shiny.rstudio.com/articles/layout-guide.html
## http://rmarkdown.rstudio.com/authoring_shiny.html
## http://shiny.rstudio.com/images/shiny-cheatsheet.pdf
## http://shiny.rstudio.com/tutorial
## http://rstudio.github.io/shinythemes/

## Ideas for cool add-ons: 
##  -- DT::dataTableOutput() for interactive table
##  -- leaflet for interactive maps
##  -- flexdashboard for interactive dashboards
##  -- ggplotly for interactive ggplot2 graphics

## Two most common "why isn't my app running?!" problems:
## (1) comma-separate all the elements
## (2) do not add comma to the last element


#=============================================================
## Next time: 
## Machine learning in R, clustering (K-means, hierarchical clustering),
##   data mining
#=============================================================

```

```{r, echo=F}
#It is very important that the name of the file is app.R, otherwise it would not be recognized as a Shiny app.
#You should not have any R code after the shinyApp(ui = ui, server = server) line. That line needs to be the last line in your file.
#It is good practice to place this app in its own folder, and not in a folder that already has other R scripts or files, unless those other files are used by your app.

sliderInput("num", "Choose a number",
            0, 100, 20)

renderPlot({
    plot(seq(input$num))
})

```
